### ISSUE TITLE
How can I get only the status bar working?

### ISSUE THREAD

**Issue by nilsi** [camspiers/dotfiles#10]
Hi,

Thank you for the awesome inspiration from your dotfiles! 

I'm trying to get your Ubersicht setup working with my machine.

I'm already using yabai like your setup but wonder how to integrate ubersicht with it.

What I did so far is to install Ubersicht -> open widgets folder -> paste everything from yours `.config/unbersicht` into my widgets folder.

Result:

![Screenshot 2020-10-05 at 11 54 56](https://user-images.githubusercontent.com/793881/95067522-43947b00-0704-11eb-98ee-99fb1c4d0e03.jpg)

**Comment by camspiers** [comment]
I abandoned Ubersicht, it's a terrible resource hog and in my view not a recommended piece of software.
