### ISSUE TITLE
"vim-plug" not installed

### ISSUE THREAD

**Issue by justinmoon** [camspiers/dotfiles#2]
Running `:PlugInstall` fails -- seems like the plug script isn't installed.

Perhaps you'd want to include this [this](https://github.com/junegunn/vim-plug#neovim) somewhere in your build scripts?

**Comment by camspiers** [comment]
You are probably right that there is an issue here, but did you run:

https://github.com/camspiers/dotfiles/blob/master/Makefile#L12
