### ISSUE TITLE
Status bar doesn't show up

### ISSUE THREAD

**Issue by justinmoon** [camspiers/dotfiles#4]
Here's what my desktop looks like after installing and restarting

<img width="1440" alt="Screen Shot 2019-12-29 at 7 22 27 PM" src="https://user-images.githubusercontent.com/4335621/71565106-a3bd0900-2a70-11ea-8159-df859e716577.png">

Beautiful task bar shown in you screenshots doesn't show up.

Another question -- is it supposed to replace the default Mac bar at the top of the screen or go directly below it?

**Comment by camspiers** [comment]
Did you install Ubersicht via brew? Make sure it is running. You want to also hide the menu bar at the top.

http://www.iphonehacks.com/2017/05/automatically-hide-the-menu-bar-on-mac.html

**Comment by camspiers** [comment]
Try the latest commits...
