### ISSUE TITLE
activeSpaceServer.js causes high CPU use unless launched manually

### ISSUE THREAD

**Issue by d-miketa** [camspiers/dotfiles#9]
I was intrigued by your active space solution and got it working on my machine. It runs as I imagine yours does, with a small but annoying hitch: I need to run `node path/to/activeSpaceServer.js` manually in the terminal, otherwise CPU use skyrockets. The debug console reveals that the space widget cannot connect to `127.0.0.1:15997`.

Not sure why this is so, perhaps
```
activeSpace.onerror = () => {
    // Failed to connect, start the activeSpaceServer then init again
    run('node ./lib/activeSpaceServer.js &').then(() => init(dispatch));
};
```
is getting triggered over and over again and although node no longer complains that it can't start the server (I had to tweak the file name and location a bit), could be that it immediately exits?

I'd be grateful for any help, the Swift backend is, well, truly much swifter. :)

**Comment by camspiers** [comment]
I'm unsure, but I no longer use ubersicht as it is a huge resource hog. I just use yabai with its status bar.
